# pennbauman.com site

[[page]]
path = "/site.html"
context = { title = "Site - Penn Bauman", description = "Site information for pennbauman.com", robots = "noindex,nofollow" }

[[redirect]]
path = "/github.html"
url = "https://github.com/pennbauman"

[[redirect]]
path = "/resume.html"
url = "/files/pennbauman_resume.pdf"
