# pennbauman.com site

[[page]]
path = "/about.html"
context = { title = "About - Penn Bauman", description = "Penn Bauman is currently attening The University of Virginia. He is majoring Computer Science in the School of Engineering, and minoring in Physics." }

[[page]]
path = "/site.html"
context = { title = "Site - Penn Bauman", description = "Site information for pennbauman.com", robots = "noindex,nofollow" }

[[redirect]]
path = "/github.html"
url = "https://github.com/pennbauman"

[[redirect]]
path = "/resume.html"
url = "/files/Penn_Bauman_Resume.pdf"
