<?php
/* Element Information for /projects/periodic-table
*/
	$elements = [
		["Sym", "Name", "Mass", "Type", "classes", "solid", "Nonradioactive"],
		/*
		0 = Sym
		1 = Name
		2 = Mass
		3 = Type
		4 = CSS Classes 
		*/
		["H", "Hydrogen", "1.008", "Nonmetal", "nonmetal row1 col1", "gas", "Nonradioactive"],
		["He", "Helium", "4.003", "Noble Gas", "noble row1 col18", "gas", "Nonradioactive"],

		["Li", "Lithium", "6.941", "Alkali Metal", "alkali row2 col1", "solid", "Nonradioactive"],
		["Be", "Beryllium", "9.012", "Alkaline Earth Metal", "alkaline row2 col2", "solid", "Nonradioactive"],
		["B", "Boron", "10.811", "Metaloid", "metaloid row2 col13", "solid", "Nonradioactive"],
		["C", "Carbon", "12.011", "Nonmetal", "nonmetal row2 col14", "solid", "Nonradioactive"],
		["N", "Nitrogen", "14.007", "Nonmetal", "nonmetal row2 col15", "gas", "Nonradioactive"],
		["O", "Oxygen", "15.999", "Nonmetal", "nonmetal row2 col16", "gas", "Nonradioactive"],
		["F", "Flourine", "18.998", "Halogen", "halogen row2 col17", "gas", "Nonradioactive"],
		["Ne", "Neon", "20.180", "Noble Gas", "noble row2 col18", "gas", "Nonradioactive"],

		["Na", "Sodium", "22.990", "Alkali Metal", "alkali row3 col1", "solid", "Nonradioactive"],
		["Mg", "Magnesium", "24.305", "Alkaline Earth Metal", "alkaline row3 col2", "solid", "Nonradioactive"],
		["Al", "Aluminum", "26.982", "Basic Metal", "metal row3 col13", "solid", "Nonradioactive"],
		["Si", "Silicon", "28.086", "Metaloid", "metaloid row3 col14", "solid", "Nonradioactive"],
		["P", "Phosphorus", "30.974", "Nonmetal", "nonmetal row3 col15", "solid", "Nonradioactive"],
		["S", "Sulfur", "32.066", "Nonmetal", "nonmetal row3 col16", "solid", "Nonradioactive"],
		["Cl", "Chlorine", "35.453", "Halogen", "halogen row3 col17", "gas", "Nonradioactive"],
		["Ar", "Argon", "39.948", "Noble Gas", "noble row3 col18", "gas", "Nonradioactive"],

		["K", "Potassium", "39.098", "Alkali Metal", "alkali row4 col1", "solid", "Nonradioactive"],
		["Ca", "Calcium", "40.078", "Alkaline Earth Metal", "alkaline row4 col2", "solid", "Nonradioactive"],
		["Sc", "Scandium", "44.956", "Transition Metal", "transmetal row4 col3", "solid", "Nonradioactive"],
		["Ti", "Titanium", "47.880", "Transition Metal", "transmetal row4 col4", "solid", "Nonradioactive"],
		["V", "Vanadium", "50.942", "Transition Metal", "transmetal row4 col5", "solid", "Nonradioactive"],
		["Cr", "Chromium", "51.996", "Transition Metal", "transmetal row4 col6", "solid", "Nonradioactive"],
		["Mn", "Manganese", "54.938", "Transition Metal", "transmetal row4 col7", "solid", "Nonradioactive"],
		["Fe", "Iron", "55.933", "Transition Metal", "transmetal row4 col8", "solid", "Nonradioactive"],
		["Co", "Cobalt", "58.933", "Transition Metal", "transmetal row4 col9", "solid", "Nonradioactive"],
		["Ni", "Nickel", "58.693", "Transition Metal", "transmetal row4 col10", "solid", "Nonradioactive"],
		["Cu", "Copper", "63.546", "Transition Metal", "transmetal row4 col11", "solid", "Nonradioactive"],
		["Zn", "Zinc", "65.390", "Transition Metal", "transmetal row4 col12", "solid", "Nonradioactive"],
		["Ga", "Gallium", "69.732", "Basic Metal", "metal row4 col13", "solid", "Nonradioactive"],
		["Ge", "Germanium", "72.610", "Metaloid", "metaloid row4 col14", "solid", "Nonradioactive"],
		["As", "Arsenic", "74.922", "Metaloid", "metaloid row4 col15", "solid", "Nonradioactive"],
		["Se", "Selenium", "78.090", "Nonmetal", "nonmetal row4 col16", "solid", "Nonradioactive"],
		["Br", "Bromine", "79.904", "Halogen", "halogen row4 col17", "liqud", "Nonradioactive"],
		["Kr", "Krypton", "84.800", "Noble Gas", "noble row4 col18", "gas", "Nonradioactive"],

		["Rb", "Rubidium", "84.468", "Alkali Metal", "alkali row5 col1", "solid", "Nonradioactive"],
		["Sr", "Strontium", "87.620", "Alkaline Earth Metal", "alkaline row5 col2", "solid", "Nonradioactive"],
		["Y", "Yttrium", "88.906", "Transition Metal", "transmetal row5 col3", "solid", "Nonradioactive"],
		["Zr", "Zirconium", "91.224", "Transition Metal", "transmetal row5 col4", "solid", "Nonradioactive"],
		["Nb", "Niobium", "92.906", "Transition Metal", "transmetal row5 col5", "solid", "Nonradioactive"],
		["Mo", "Molybdenum", "95.940", "Transition Metal", "transmetal row5 col6", "solid", "Nonradioactive"],
		["Tc", "Technetium", "98.907", "Transition Metal", "transmetal row5 col7", "solid", "Nonradioactive"],
		["Ru", "Ruthenium", "101.070", "Transition Metal", "transmetal row5 col8", "solid", "Nonradioactive"],
		["Rh", "Rhodium", "102.906", "Transition Metal", "transmetal row5 col9", "solid", "Nonradioactive"],
		["Pd", "Palladium", "106.420", "Transition Metal", "transmetal row5 col10", "solid", "Nonradioactive"],
		["Ag", "Silver", "107.868", "Transition Metal", "transmetal row5 col11", "solid", "Nonradioactive"],
		["Cd", "Cadmium", "112.411", "Transition Metal", "transmetal row5 col12", "solid", "Nonradioactive"],
		["In", "Indium", "114.818", "Basic Metal", "metal row5 col13", "solid", "Nonradioactive"],
		["Sn", "Tin", "118.710", "Basic Metal", "metal row5 col14", "solid", "Nonradioactive"],
		["Sb", "Antimony", "121.760", "Metaloid", "metaloid row5 col15", "solid", "Nonradioactive"],
		["Te", "Tellurium", "127.600", "Metaloid", "metaloid row5 col16", "solid", "Nonradioactive"],
		["I", "Iodine", "126.904", "Halogen", "halogen row5 col17", "solid", "Nonradioactive"],
		["Xe", "Xenon", "131.290", "Noble Gas", "noble row5 col18", "gas", "Nonradioactive"],

		["Cs", "Ceslium", "132.905", "Alkali Metal", "alkali row6 col1", "solid", "Nonradioactive"],
		["Ba", "Barium", "137.327", "Alkaline Earth Metal", "alkaline row6 col2", "solid", "Nonradioactive"],

		["La", "Lanthanum", "138.906", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Ce", "Cerium", "140.115", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Pr", "Praseodymium", "140.908", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Nd", "Neodymium", "144.240", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Pm", "Promethium", "144.913", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Sm", "Samarium", "150.360", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Eu", "Europium", "151.966", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Gd", "Gadolinium", "157.250", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Tb", "Terbium", "158.925", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Dy", "Dysprosium", "162.500", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Ho", "Holmium", "164.930", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Er", "Erbium", "167.260", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Tm", "Thulium", "168.934", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Yb", "Ytterbium", "173.040", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],
		["Lu", "Lutetium", "174.967", "Lanthanide", "lanthanide row6", "solid", "Nonradioactive"],

		["Hf", "Hafnium", "178.490", "Transition Metal", "transmetal row6 col4", "solid", "Nonradioactive"],
		["Ta", "Tantalum", "180.948", "Transition Metal", "transmetal row6 col5", "solid", "Nonradioactive"],
		["W", "Tungsten", "183.850", "Transition Metal", "transmetal row6 col6", "solid", "Nonradioactive"],
		["Re", "Rhenium", "168.207", "Transition Metal", "transmetal row6 col7", "solid", "Nonradioactive"],
		["Os", "Osmium", "190.230", "Transition Metal", "transmetal row6 col8", "solid", "Nonradioactive"],
		["Ir", "Iridium", "192.220", "Transition Metal", "transmetal row6 col9", "solid", "Nonradioactive"],
		["Pt", "Platinum", "195.080", "Transition Metal", "transmetal row6 col10", "solid", "Nonradioactive"],
		["Au", "Gold", "196.967", "Transition Metal", "transmetal row6 col11", "solid", "Nonradioactive"],
		["Hg", "Mercury", "200.590", "Transition Metal", "transmetal row6 col12", "liquid", "Nonradioactive"],
		["Tl", "Thallium", "204.383", "Basic Metal", "metal row6 col13", "solid", "Nonradioactive"],
		["Pb", "Lead", "207.200", "Basic Metal", "metal row6 col14", "solid", "Nonradioactive"],
		["Bi", "Bismuth", "208.980", "Basic Metal", "metal row6 col15", "solid", "Nonradioactive"],
		["Po", "Polonium", "208.982", "Metaloid", "metaloid row6 col16", "solid", "Radioactive"],
		["At", "Astantine", "209.987", "Halogen", "halogen row6 col17", "solid", "Radioactive"],
		["Rn", "Radon", "222.018", "Noble Gas", "noble row6 col18", "gas", "Radioactive"],

		["Fr", "Francium", "223.020", "Alkali Metal", "alkali row7 col1", "solid", "Radioactive"],
		["Ra", "Radium", "226.025", "Alkaline Earth Metal", "alkaline row7 col2", "solid", "Radioactive"],

		["Ac", "Actinium", "227.028", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Th", "Thornium", "232.038", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Pa", "Protactinium", "231,036", "Actinide", "actinide row7", "solid", "Radioactive"],
		["U", "Uranium", "238.029", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Np", "Neptunium", "237.048", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Pu", "Plutonium", "244.064", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Am", "Americium", "243.061", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Cm", "Curium", "247.070", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Bk", "Berkelium", "247.070", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Cf", "Californium", "251.080", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Es", "Einsteinium", "[254]", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Fm", "Fernium", "257.095", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Md", "Mendelevium", "258.100", "Actinide", "actinide row7", "solid", "Radioactive"],
		["No", "Nobelium", "258.101", "Actinide", "actinide row7", "solid", "Radioactive"],
		["Lr", "Lawrencium", "[262]", "Actinide", "actinide row7", "solid", "Radioactive"],

		["Rf", "Rutherfordium", "[261]", "Transition Metal", "transmetal row7 col4", "unknown", "Radioactive"],
		["Db", "Dubnium", "[262]", "Transition Metal", "transmetal row7 col5", "unknown", "Radioactive"],
		["Sg", "Seaborgium", "[266]", "Transition Metal", "transmetal row7 col6", "unknown", "Radioactive"],
		["Bh", "Bohrium", "[264]", "Transition Metal", "transmetal row7 col7", "unknown", "Radioactive"],
		["Hs", "Hassium", "[269]", "Transition Metal", "transmetal row7 col8", "unknown", "Radioactive"],
		["Mt", "Meitnerium", "[268]", "Transition Metal", "transmetal row7 col9", "unknown", "Radioactive"],
		["Ds", "Darmstadium", "[269]", "Transition Metal", "transmetal row7 col10", "unknown", "Radioactive"],
		["Rg", "Roentgenium", "[272]", "Transition Metal", "transmetal row7 col11", "unknown", "Radioactive"],
		["Cn", "Copernicium", "[277]", "Transition Metal", "transmetal row7 col12", "unknown", "Radioactive"],
		["Nh", "Nihonium", "[268]", "Basic Metal", "metal row7 col13", "unknown", "Radioactive"],
		["Fl", "Flerovium", "[289]", "Basic Metal", "metal row7 col14", "unknown", "Radioactive"],
		["Mc", "Moscovium", "[290]", "Basic Metal", "metal row7 col15", "unknown", "Radioactive"],
		["Lv", "Livermorium", "[298]", "Basic Metal", "metal row7 col16", "unknown", "Radioactive"],
		["Ts", "Tennessine", "[294]", "Halogen", "halogen row7 col17", "unknown", "Radioactive"],
		["Og", "Oganesson", "[294]", "Noble Gas", "noble row7 col18", "unknown", "Radioactive"],
	];
?>
