" Added by Penn

" General
filetype plugin on
set encoding=utf8
set clipboard+=unnamedplus

" Appearance
set number
set wrap lbr
set tabstop=4
set shiftwidth=4
set listchars=tab:¦\ ,trail:~,extends:>,precedes:<
set list
set guicursor=
source /home/penn/.local/share/nvim/site/colors/maia-custom.vim
" Netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" Keyboard Shortcuts
nnoremap <S-tab> :bprev<Enter>
nnoremap <tab>   :bnext<Enter>
" Document navigation
noremap <silent> k gk
noremap <silent> j gj
noremap <silent> <S-h> g^
noremap <silent> <S-j> 15gj
noremap <silent> <S-k> 15gk
noremap <silent> <S-l> g$
nmap <S-u> :redo<Enter>
" Editing
nmap <enter> o<esc>
nmap ; :
nmap < v<
nmap > v>
nmap <S-d> dd
vmap <S-y> ! xsel -b<enter>u
