" Added by Penn
filetype plugin on
set number
set wrap lbr
nnoremap <S-tab> :bprev<Enter>
nnoremap <tab>   :bnext<Enter>
" document navigation
noremap <silent> k gk
noremap <silent> j gj
noremap <silent> <S-h> g^
noremap <silent> <S-j> 15gj
noremap <silent> <S-k> 15gk
noremap <silent> <S-l> g$
nmap <S-u> :redo<Enter>
" editing
nmap <enter> i<enter><esc>
nmap <S-i> i<end>
nmap ; :
nmap < v<
nmap > v>
nmap <S-o> o<esc>
nmap <S-d> dd
" copy and paste
vmap <S-y> ! xsel -b<enter>u
