<?php
	$elements = array(
		array(),
		array("H", "Hydrogen", "1.008", "Nonmetal", "nonmetal row1 col1"),
		array("He", "Helium", "4.003", "Noble Gas", "noble row1 col18"),

		array("Li", "Lithium", "6.941", "Alkali Metal", "alkali row2 col1"),
		array("Be", "Beryllium", "9.012", "Alkaline Earth Metal", "alkaline row2 col2"),
		array("B", "Boron", "10.811", "Metaloid", "meraloid row2 col13"),
		array("C", "Carbon", "12.011", "Nonmetal", "nonmetal row2 col14"),
		array("N", "Nitrogen", "14.007", "Nonmetal", "nonmetal row2 col15"),
		array("O", "Oxygen", "15.999", "Nonmetal", "nonmetal row2 col16"),
		array("F", "Flourine", "18.998", "Halogen", "halogen row2 col17"),
		array("Ne", "Neon", "20.180", "Noble Gas", "noble row2 col18"),

		array("Na", "Sodium", "22.990", "Alkali Metal", "alkali row3 col1"),
		array("Mg", "Magnesium", "24.305", "Alkaline Earth Metal", "alkaline row3 col2"),
		array("Al", "Aluminum", "26.982", "Basic Metal", "metal row3 col13"),
		array("Si", "Silicon", "28.086", "Metaloid", "metaloid row3 col14"),
		array("P", "Phosphorus", "30.974", "Nonmetal", "nonmetal row3 col15"),
		array("S", "Sulfur", "32.066", "Nonmetal", "nonmetal row3 col16"),
		array("Cl", "Chlorine", "35.453", "Halogen", "halogen row3 col17"),
		array("Ar", "Argon", "39.948", "Noble Gas", "noble row3 col18"),

		array("K", "Potassium", "39.098", "Alkali Metal", "alkali row4 col1"),
		array("Ca", "Calcium", "40.078", "Alkaline Earth Metal", "alkaline row4 col2"),
		array("Sc", "Scandium", "44.956", "Transition Metal", "transmetal row4 col3"),
		array("Ti", "Titanium", "47.880", "Transition Metal", "transmetal row4 col4"),
		array("V", "Vanadium", "50.942", "Transition Metal", "transmetal row4 col5"),
		array("Cr", "Chromium", "51.996", "Transition Metal", "transmetal row4 col6"),
		array("Mn", "Manganese", "54.938", "Transition Metal", "transmetal row4 col7"),
		array("Fe", "Iron", "55.933", "Transition Metal", "transmetal row4 col8"),
		array("Co", "Cobalt", "58.933", "Transition Metal", "transmetal row4 col9"),
		array("Ni", "Nickel", "58.693", "Transition Metal", "transmetal row4 col10"),
		array("Cu", "Copper", "63.546", "Transition Metal", "transmetal row4 col11"),
		array("Zn", "Zinc", "65.390", "Transition Metal", "transmetal row4 col12"),
		array("Ga", "Gallium", "69.732", "Basic Metal", "metal row4 col13"),
		array("Ge", "Germanium", "72.610", "Metaloid", "metaloid row4 col14"),
		array("As", "Arsenic", "74.922", "Metaloid", "metaloid row4 col15"),
		array("Se", "Selenium", "78.090", "Nonmetal", "nonmetal row4 col16"),
		array("Br", "Bromine", "79.904", "Halogen", "halogen row4 col17"),
		array("Kr", "Krypton", "84.800", "Noble Gas", "noble row4 col18"),

		array("Rb", "Rubidium", "84.468", "Alkali Metal", "alkali row5 col1"),
		array("Sr", "Strontium", "87.620", "Alkaline Earth Metal", "alkaline row5 col2"),
		array("Y", "Yttrium", "88.906", "Transition Metal", "transmetal row5 col3"),
		array("Zr", "Zirconium", "91.224", "Transition Metal", "transmetal row5 col4"),
		array("Nb", "Niobium", "92.906", "Transition Metal", "transmetal row5 col5"),
		array("Mo", "Molybdenum", "95.940", "Transition Metal", "transmetal row5 col6"),
		array("Tc", "Technetium", "98.907", "Transition Metal", "transmetal row5 col7"),
		array("Ru", "Ruthenium", "101.070", "Transition Metal", "transmetal row5 col8"),
		array("Rh", "Rhodium", "102.906", "Transition Metal", "transmetal row5 col9"),
		array("Pd", "Palladium", "106.420", "Transition Metal", "transmetal row5 col10"),
		array("Ag", "Silver", "107.868", "Transition Metal", "transmetal row5 col11"),
		array("Cd", "Cadmium", "112.411", "Transition Metal", "transmetal row5 col12"),
		array("In", "Indium", "114.818", "Basic Metal", "metal row5 col13"),
		array("Sn", "Tin", "118.710", "Basic Metal", "metal row5 col14"),
		array("Sb", "Antimony", "121.760", "Metaloid", "metaloid row5 col15"),
		array("Te", "Tellurium", "127.600", "Metaloid", "metaloid row5 col16"),
		array("I", "Iodine", "126.904", "Halogen", "halogen row5 col17"),
		array("Xe", "Xenon", "131.290", "Noble Gas", "noble row5 col18"),

		array("Cs", "Ceslium", "132.905", "Alkali Metal", "alkali row6 col1"),
		array("Ba", "Barium", "137.327", "Alkaline Earth Metal", "alkaline row6 col2"),

		array("La", "Lanthanum", "138.906", "Lanthanide", "lanthanide row6"),
		array("Ce", "Cerium", "140.115", "Lanthanide", "lanthanide row6"),
		array("Pr", "Praseodymium", "140.908", "Lanthanide", "lanthanide row6"),
		array("Nd", "Neodymium", "144.240", "Lanthanide", "lanthanide row6"),
		array("Pm", "Promethium", "144.913", "Lanthanide", "lanthanide row6"),
		array("Sm", "Samarium", "150.360", "Lanthanide", "lanthanide row6"),
		array("Eu", "Europium", "151.966", "Lanthanide", "lanthanide row6"),
		array("Gd", "Gadolinium", "157.250", "Lanthanide", "lanthanide row6"),
		array("Tb", "Terbium", "158.925", "Lanthanide", "lanthanide row6"),
		array("Dy", "Dysprosium", "162.500", "Lanthanide", "lanthanide row6"),
		array("Ho", "Holmium", "164.930", "Lanthanide", "lanthanide row6"),
		array("Er", "Erbium", "167.260", "Lanthanide", "lanthanide row6"),
		array("Tm", "Thulium", "168.934", "Lanthanide", "lanthanide row6"),
		array("Yb", "Ytterbium", "173.040", "Lanthanide", "lanthanide row6"),
		array("Lu", "Lutetium", "174.", "Lanthanide", "lanthanide row6"),

		array("Hf", "Hafnium", "178.490", "Transition Metal", "transmetal row6 col4"),
		array("Ta", "Tantalum", "180.948", "Transition Metal", "transmetal row6 col5"),
		array("W", "Tungsten", "183.850", "Transition Metal", "transmetal row6 col6"),
		array("Re", "Rhenium", "168.207", "Transition Metal", "transmetal row6 col7"),
		array("Os", "Osmium", "190.230", "Transition Metal", "transmetal row6 col8"),
		array("Ir", "Iridium", "192.220", "Transition Metal", "transmetal row6 col9"),
		array("Pt", "Platinum", "195.080", "Transition Metal", "transmetal row6 col10"),
		array("Au", "Gold", "196.967", "Transition Metal", "transmetal row6 col11"),
		array("Hg", "Mercury", "200.590", "Transition Metal", "transmetal row6 col12"),
		array("Tl", "Thallium", "204.383", "Basic Metal", "metal row6 col13"),
		array("Pb", "Lead", "207.200", "Basic Metal", "metal row6 col14"),
		array("Bi", "Bismuth", "208.980", "Basic Metal", "metal row6 col15"),
		array("Po", "Polonium", "208.982", "Metaloid", "metaloid row6 col16"),
		array("At", "Astantine", "209.987", "Halogen", "halogen row6 col17"),
		array("Rn", "Radon", "222.018", "Noble Gas", "noble row6 col18"),

		array("Fr", "Francium", "223.020", "Alkali Metal", "alkali row7 col1"),
		array("Ra", "Radium", "226.025", "Alkaline Earth Metal", "alkaline row7 col2"),

		array("Ac", "Actinium", "227.028", "Actinide", "actinide row7"),
		array("Th", "Thornium", "232.038", "Actinide", "actinide row7"),
		array("Pa", "Protactinium", "231,036", "Actinide", "actinide row7"),
		array("U", "Uranium", "238.029", "Actinide", "actinide row7"),
		array("Np", "Neptunium", "237.048", "Actinide", "actinide row7"),
		array("Pu", "Plutonium", "244.064", "Actinide", "actinide row7"),
		array("Am", "Americium", "243.061", "Actinide", "actinide row7"),
		array("Cm", "Curium", "247.070", "Actinide", "actinide row7"),
		array("Bk", "Berkelium", "247.070", "Actinide", "actinide row7"),
		array("Cf", "Californium", "251.080", "Actinide", "actinide row7"),
		array("Es", "Einsteinium", "254)", "Actinide", "actinide row7"),
		array("Fm", "Fernium", "257.095", "Actinide", "actinide row7"),
		array("Md", "Mendelevium", "258.100", "Actinide", "actinide row7"),
		array("No", "Nobelium", "258.101", "Actinide", "actinide row7"),
		array("Lr", "Lawrencium", "262)", "Actinide", "actinide row7"),

		array("Rf", "Rutherfordium", "261)", "Transition Metal", "transmetal row7 col4"),
		array("Db", "Dubnium", "262)", "Transition Metal", "transmetal row7 col5"),
		array("Sg", "Seaborgium", "266)", "Transition Metal", "transmetal row7 col6"),
		array("Bh", "Bohrium", "264)", "Transition Metal", "transmetal row7 col7"),
		array("Hs", "Hassium", "269)", "Transition Metal", "transmetal row7 col8"),
		array("Mt", "Meitnerium", "268)", "Transition Metal", "transmetal row7 col9"),
		array("Ds", "Darmstadium", "269)", "Transition Metal", "transmetal row7 col10"),
		array("Rg", "Roentgenium", "272)", "Transition Metal", "transmetal row7 col11"),
		array("Cn", "Copernicium", "277)", "Transition Metal", "transmetal row7 col12"),
		array("Uut", "Ununtrium", "unknown", "Basic Metal", "metal row7 col13"),
		array("Fl", "Flerovium", "289)", "Basic Metal", "metal row7 col14"),
		array("Uup", "Ununpentium", "unknown", "Basic Metal", "metal row7 col15"),
		array("Lv", "Livermorium", "298)", "Basic Metal", "metal row7 col16"),
		array("Uus", "Ununseptium", "unknown", "Halogen", "halogen row7 col17"),
		array("Uuo", "Ununoctium", "unknown", "Noble Gas", "noble row7 col18"),
	);
	echo "<h1>HI</h1>";
?>
